# Generated by Django 2.1.7 on 2019-11-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0003_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='val',
            field=models.IntegerField(default=0),
        ),
    ]
