# Generated by Django 2.1.7 on 2019-11-12 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0004_counter_val'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counter',
            old_name='val',
            new_name='value',
        ),
    ]
