# Generated by Django 2.1.7 on 2019-11-12 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0005_auto_20191112_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counter',
            old_name='value',
            new_name='_state',
        ),
    ]
