# Generated by Django 2.1.7 on 2019-11-12 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0006_auto_20191112_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counter',
            old_name='_state',
            new_name='value',
        ),
    ]
