# Generated by Django 2.1.7 on 2019-11-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0007_auto_20191112_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
