# Generated by Django 2.1.7 on 2019-11-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0009_auto_20191112_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
