# Generated by Django 2.1.7 on 2019-11-21 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0010_auto_20191112_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='value',
        ),
    ]
