# Generated by Django 2.2.7 on 2019-11-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0011_remove_counter_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
